---
title: "Gov 50 Final Project"
author: "Courtney Taylor"
description: "My final project"
output:
  distill::distill_article:
    self_contained: false
---



## Project thoughts

Milestone 1: Create public GitHub repository: I am interested in exploring data related to analyze the correlation between the percentage of men who come to womens sporting events and the amount of coverage womens sports get on sports stations. If this idea does not work, then I will look into the correlation between location within the united states and the political party people associate with. My third idea would be to analyze the correlation between the enaction of Roe v. Wade and the amount of births occuring within the United States, as well as the repeal of Roe v. Wade and the amount of births occuring within the United States.




Milestone 2: Finding data and writing a proposal: Does nutrition and physical activity affect whether or not someone becomes obese? I plan to examine the extent to which people need to have good nutrition and physical activity to not become obese. 

I hypothesize that good nutrition has a large effect on if someone becomes obese, while physical activity only has a small effect on if someone becomes obese. If people were to have good nutrition with no physical activity, I expect there would be a lower percentage of those who are obese. If people were to do physical activity but have bad nutrition, then I believe the percentage of those who are obese would be higher. This hypothesis could be true as for example, those who have remote jobs and may not have time to do physical activity, if they eat well and have good nutrition, it would be unlikely that they get to a point of obesity. On the other hand, those who play sports and do physical activity, but have bad nutrition and eat unhealthy food, will be more likely to gain weight and become obese. 

The explanatory variable of interest is whether subjects engage in good or bad nutrition and if they engage in physical activity. This variable will be measured through graphs and percentages. The possible variations in this variable could be gender and age. 

The outcome variable is whether or not the subject is obese. For instance, I will be examining if the outcome of obesity is affected by the subject’s nutrition and physical activity. This variable is measured by the “Nutrition, Physical Activity, and Obesity - Behavioral Risk Factor Surveillance System” from the U.S. Department of Health & Human Services. 

If observe that there is a small percentage of obesity in those who have good nutrition but little to no physical activity, then my hypothesis would be supported. My hypothesis would also be supported if I observed that there is a greater percentage of obesity in those with bad nutrition but a lot of physical activity. On the other hand, if I observe that there is a greater percentage of obesity in those who have good nutrition but little to no physical activity, then this would provide evidence against my hypothesis. My hypothesis would also be null if I observed that there is a smaller percentage of obesity in those with bad nutrition but a lot of physical activity.